services:
  app:
    image: qqbot:v0.0.2
    ports:
      - "2077:2077"
    depends_on:
      - db
      - redis
  db:
    image: postgres:15.6
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: bsbflsgxh..
      POSTGRES_DB: qq_bot
    ports:
      - "5432:5432"
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
